-- No sample / Acme seed data.
-- Accounts start empty; workspaces and org members come from real onboarding only.
-- supabase db reset still loads this file when configured — keep it intentionally blank.
