import type {
  AccountPresetId,
  AssetFile,
  Connector,
  ConnectorAccount,
  Member,
  PlatformDeployment,
  PlatformNav,
  Project,
  ScheduledJob,
  Skill,
  SpaceId,
  Thread,
  Workspace,
  WorkspaceResource,
} from "./types";

export const account = {
  id: "acme",
  name: "Acme Inc.",
  seats: 6,
};

function person(
  row: Omit<Member, "short" | "initials"> & { short?: string },
): Member {
  const first = row.name.split(" ")[0] ?? row.name;
  const initials = row.name
    .split(" ")
    .map((part) => part[0])
    .join("")
    .slice(0, 2)
    .toUpperCase();
  return {
    ...row,
    short: row.short ?? first,
    initials,
  };
}

export const members: Member[] = [
  person({
    id: "m1",
    name: "Matthew Gross",
    email: "matthew@acme.com",
    role: "Owner",
    workspaceIds: ["marketing", "engineering", "operations"],
    plan: "max",
    seatStatus: "active",
    kind: "org",
  }),
  person({
    id: "m2",
    name: "Jackson Oaks",
    email: "jackson@acme.com",
    role: "Admin",
    workspaceIds: ["marketing", "engineering", "operations"],
    plan: "max",
    seatStatus: "active",
    kind: "org",
  }),
  person({
    id: "m3",
    name: "Ryker Ross",
    email: "ryker@acme.com",
    role: "Admin",
    workspaceIds: ["engineering"],
    plan: "max",
    seatStatus: "active",
    kind: "org",
  }),
  person({
    id: "m4",
    name: "John Kim",
    email: "john@acme.com",
    role: "Member",
    workspaceIds: ["marketing", "engineering"],
    plan: "max",
    seatStatus: "active",
    kind: "org",
  }),
  person({
    id: "m5",
    name: "Amy Rivera",
    email: "amy@acme.com",
    role: "Member",
    workspaceIds: ["engineering", "operations"],
    plan: "max",
    seatStatus: "active",
    kind: "org",
  }),
  person({
    id: "m6",
    name: "Sarah Chen",
    email: "sarah@acme.com",
    role: "Member",
    workspaceIds: ["engineering", "operations"],
    plan: "ultra",
    seatStatus: "active",
    kind: "org",
  }),
  person({
    id: "m7",
    name: "Mike Singh",
    email: "mike@acme.com",
    role: "Member",
    workspaceIds: ["marketing"],
    plan: "pro",
    seatStatus: "active",
    kind: "org",
  }),
  person({
    id: "p-pro",
    name: "Maya Singh",
    email: "maya@example.com",
    role: "Member",
    workspaceIds: ["solo-pro"],
    plan: "pro",
    seatStatus: "pending",
    kind: "org",
  }),
  person({
    id: "p-ultra",
    name: "Jordan Hale",
    email: "jordan@example.com",
    role: "Member",
    workspaceIds: ["solo-ultra"],
    plan: "ultra",
    seatStatus: "pending",
    kind: "org",
  }),
  person({
    id: "p-free",
    name: "Eli Brooks",
    email: "eli@example.com",
    role: "Member",
    workspaceIds: ["solo-free"],
    plan: "free",
    seatStatus: "pending",
    kind: "org",
  }),
];

export const currentUser = members[0];
export const currentUserId = currentUser.id;

export const accountPresets: {
  id: AccountPresetId;
  label: string;
  actorId: string;
  hint: string;
  group: "Organization" | "Personal";
}[] = [
  {
    id: "max-owner",
    label: "Max Owner",
    actorId: "m1",
    hint: "Billing and mixed org seats",
    group: "Organization",
  },
  {
    id: "max-admin",
    label: "Max Admin",
    actorId: "m3",
    hint: "People and workspaces, not billing",
    group: "Organization",
  },
  {
    id: "max-member",
    label: "Max Member",
    actorId: "m4",
    hint: "John · shared workspaces and team dev",
    group: "Organization",
  },
  {
    id: "ultra-member",
    label: "Ultra Member",
    actorId: "m6",
    hint: "Sarah · production infrastructure",
    group: "Organization",
  },
  {
    id: "pro",
    label: "Pro",
    actorId: "p-pro",
    hint: "Personal Pro · Acme invite locked",
    group: "Personal",
  },
  {
    id: "ultra",
    label: "Ultra",
    actorId: "p-ultra",
    hint: "Personal Ultra · invite still locked",
    group: "Personal",
  },
  {
    id: "free",
    label: "Free",
    actorId: "p-free",
    hint: "Cloud only · no Development",
    group: "Personal",
  },
];

export const workspaceResources: WorkspaceResource[] = [
  {
    id: "wr-acme-local-llm",
    workspaceId: "engineering",
    kind: "model",
    name: "Acme Local LLM",
    createdBy: "m6",
    ownerId: "m6",
    hosting: "local",
    environment: "production",
    authorizedMemberIds: ["m4", "m5", "m7"],
    status: "active",
  },
  {
    id: "wr-acme-api-gateway",
    workspaceId: "engineering",
    kind: "api",
    name: "Acme API Gateway",
    createdBy: "m6",
    ownerId: "m6",
    hosting: "cloud",
    environment: "production",
    authorizedMemberIds: ["m4", "m5"],
    status: "active",
  },
];

export const platformNavItems: { id: PlatformNav; label: string }[] = [
  { id: "overview", label: "Overview" },
  { id: "hosting", label: "Hosting" },
  { id: "models", label: "Models" },
  { id: "api", label: "APIs" },
  { id: "keys", label: "Keys" },
  { id: "deployments", label: "Deployments" },
  { id: "logs", label: "Logs" },
  { id: "usage", label: "Usage" },
  { id: "docs", label: "Docs" },
  { id: "recents", label: "Recents" },
];

export const spaces: { id: SpaceId; label: string }[] = [
  { id: "work", label: "Work" },
  { id: "build", label: "Build" },
  { id: "studio", label: "Studio" },
  { id: "research", label: "Research" },
  { id: "personal", label: "Personal" },
  { id: "files", label: "Files" },
  { id: "skills", label: "Tasks" },
  { id: "finances", label: "Finances" },
  { id: "health", label: "Health" },
  { id: "connectors", label: "Connectors" },
  { id: "scheduled", label: "Scheduled" },
];

export const workspaces: Workspace[] = [
  {
    id: "marketing",
    name: "Marketing",
    spaces: [
      "work",
      "build",
      "studio",
      "research",
      "personal",
      "connectors",
    ],
    members: 12,
    budget: "$4,200",
    spend: "$2,640",
  },
  {
    id: "engineering",
    name: "Engineering",
    spaces: ["work", "build", "research", "personal", "connectors"],
    members: 18,
    budget: "$6,800",
    spend: "$4,110",
  },
  {
    id: "operations",
    name: "Operations",
    spaces: ["work", "research", "personal", "connectors"],
    members: 8,
    budget: "$1,400",
    spend: "$890",
  },
  {
    id: "solo-pro",
    name: "Personal",
    personal: true,
    spaces: ["build", "studio", "research", "personal", "connectors"],
    members: 1,
    budget: "$0",
    spend: "$0",
  },
  {
    id: "solo-ultra",
    name: "Personal",
    personal: true,
    spaces: ["build", "studio", "research", "personal", "connectors"],
    members: 1,
    budget: "$0",
    spend: "$0",
  },
  {
    id: "solo-free",
    name: "Personal",
    personal: true,
    spaces: ["build", "studio", "research", "personal", "connectors"],
    members: 1,
    budget: "$0",
    spend: "$0",
  },
];

export const projects: Project[] = [
  {
    id: "cander",
    name: "Cander",
    space: "build",
    workspaceId: "marketing",
    summary: "Public marketing site and pricing for Cander.",
    updatedAt: "2h ago",
    domains: ["cander.com", "www.cander.com"],
    cover: "/previews/cander.png",
    threadId: "t-cander-hero",
  },
  {
    id: "starbase",
    name: "Starbase",
    space: "build",
    workspaceId: "engineering",
    summary: "Internal operator console for fleet telemetry.",
    updatedAt: "Yesterday",
    cover: "/previews/starbase.png",
  },
  {
    id: "client-portal",
    name: "Client Portal",
    space: "build",
    workspaceId: "marketing",
    summary: "Customer-facing portal for proposals and files.",
    updatedAt: "3d ago",
    domains: ["portal.acme.com"],
    cover: "/previews/portal.png",
    threadId: "t-portal",
  },
  {
    id: "launch-site",
    name: "Launch Site",
    space: "build",
    workspaceId: "marketing",
    summary: "Campaign landing pages for the next Cander drop.",
    updatedAt: "5h ago",
    cover: "/previews/launch.png",
  },
  {
    id: "field-crm",
    name: "Field CRM",
    space: "build",
    workspaceId: "marketing",
    summary: "Jobs, crews, and quotes for landscaping teams.",
    updatedAt: "6h ago",
    domains: ["app.fieldcrm.com"],
    cover: "/previews/crm.png",
  },
  {
    id: "operator-console",
    name: "Operator Console",
    space: "build",
    workspaceId: "marketing",
    summary: "Internal status board for live customer work.",
    updatedAt: "1d ago",
    cover: "/previews/console.png",
  },
  {
    id: "onboarding",
    name: "Onboarding",
    space: "build",
    workspaceId: "marketing",
    summary: "First-run flow after someone creates an account.",
    updatedAt: "2d ago",
    cover: "/previews/onboarding.png",
  },
  {
    id: "product-campaign",
    name: "Product Campaign",
    space: "studio",
    workspaceId: "marketing",
    summary: "Still photography and seasonal cutdowns.",
    updatedAt: "4h ago",
    cover: "/previews/studio-campaign.png",
    threadId: "t-campaign",
  },
  {
    id: "demo-videos",
    name: "Demo Videos",
    space: "studio",
    workspaceId: "marketing",
    summary: "Cander product walkthroughs and launch clips.",
    updatedAt: "1d ago",
    cover: "/previews/studio-demo.png",
    threadId: "t-demo",
  },
  {
    id: "competitor-research",
    name: "Competitor Research",
    space: "research",
    workspaceId: "marketing",
    summary: "Pricing, positioning, and launch cadence.",
    updatedAt: "5h ago",
    threadId: "t-competitors",
  },
  {
    id: "pricing-landscape",
    name: "Pricing Landscape",
    space: "research",
    workspaceId: "marketing",
    summary: "Seat vs token billing across the category.",
    updatedAt: "8h ago",
    threadId: "t-pricing-landscape",
  },
  {
    id: "voice-of-customer",
    name: "Voice of Customer",
    space: "research",
    workspaceId: "marketing",
    summary: "Support tickets and sales calls turned into themes.",
    updatedAt: "1d ago",
  },
  {
    id: "launch-coverage",
    name: "Launch Coverage",
    space: "research",
    workspaceId: "marketing",
    summary: "Press, partners, and what landed after Cander.",
    updatedAt: "3d ago",
  },
  {
    id: "channel-mix",
    name: "Channel Mix",
    space: "research",
    workspaceId: "marketing",
    summary: "Where inbound actually starts, week over week.",
    updatedAt: "4d ago",
  },
  {
    id: "ai-infrastructure",
    name: "AI Infrastructure",
    space: "research",
    workspaceId: "engineering",
    summary: "Local vs managed inference, tool-calling notes.",
    updatedAt: "2d ago",
  },
  {
    id: "runway",
    name: "Runway & cash",
    space: "finances",
    workspaceId: "marketing",
    summary: "Cash position, burn, and the next 18 months.",
    updatedAt: "3h ago",
  },
  {
    id: "q3-invoices",
    name: "Q3 invoices",
    space: "finances",
    workspaceId: "marketing",
    summary: "Vendor bills, approvals, and what still needs a receipt.",
    updatedAt: "Yesterday",
  },
  {
    id: "infra-spend",
    name: "Infra spend",
    space: "finances",
    workspaceId: "engineering",
    summary: "Cloud, inference, and seat costs against the engineering budget.",
    updatedAt: "1d ago",
  },
  {
    id: "ops-close",
    name: "Monthly close",
    space: "finances",
    workspaceId: "operations",
    summary: "Close checklist, accruals, and what finance still needs.",
    updatedAt: "2d ago",
  },
  {
    id: "benefits-review",
    name: "Benefits review",
    space: "health",
    workspaceId: "marketing",
    summary: "Plan comparison, open enrollment, and what people actually use.",
    updatedAt: "4h ago",
  },
  {
    id: "care-plan",
    name: "Team care plan",
    space: "health",
    workspaceId: "marketing",
    summary: "Stipends, EAP, and the quiet follow-ups after busy quarters.",
    updatedAt: "2d ago",
  },
  {
    id: "ops-wellness",
    name: "Wellness stipend",
    space: "health",
    workspaceId: "operations",
    summary: "Who has used it, what’s left, and how to remind without nagging.",
    updatedAt: "5d ago",
  },
  {
    id: "today-inbox",
    name: "Inbox — needs a reply",
    space: "work",
    workspaceId: "marketing",
    summary: "Northwind’s pricing note and two Slack threads waiting on you.",
    updatedAt: "1h ago",
  },
  {
    id: "launch-sync",
    name: "2 PM — Launch sync",
    space: "work",
    workspaceId: "marketing",
    summary: "Prep for the Cander launch meeting: open questions and last week’s notes.",
    updatedAt: "3h ago",
  },
  {
    id: "acme-renewal",
    name: "Acme renewal",
    space: "work",
    workspaceId: "marketing",
    summary: "Customer needs a proposal before Friday.",
    updatedAt: "Yesterday",
  },
  {
    id: "eng-standup",
    name: "Engineering standup",
    space: "work",
    workspaceId: "engineering",
    summary: "Blockers from overnight deploys and the on-call handoff.",
    updatedAt: "2h ago",
  },
  {
    id: "vendor-followup",
    name: "Vendor follow-ups",
    space: "work",
    workspaceId: "operations",
    summary: "Three invoices and a contract sitting in email.",
    updatedAt: "4h ago",
  },
  {
    id: "weekend-plans",
    name: "This weekend",
    space: "personal",
    workspaceId: "marketing",
    summary: "Dinner reservation and the birthday party on Saturday.",
    updatedAt: "This morning",
  },
  {
    id: "subscriptions",
    name: "Subscriptions",
    space: "personal",
    workspaceId: "marketing",
    summary: "What renews this month and what to cancel.",
    updatedAt: "2d ago",
  },
  {
    id: "annual-goals",
    name: "This year’s goals",
    space: "personal",
    workspaceId: "marketing",
    summary: "What to ship, drop, and actually finish by December.",
    updatedAt: "Yesterday",
  },
  {
    id: "car-service",
    name: "The car",
    space: "personal",
    workspaceId: "marketing",
    summary: "Registration, insurance, and the service due in October.",
    updatedAt: "5d ago",
  },
];

export const buildPreviews: {
  id: string;
  name: string;
  summary: string;
  projectId: string;
  workspaceId: string;
  updatedAt: string;
  published?: boolean;
  image?: string;
}[] = [
  {
    id: "pv-cander",
    name: "Cander",
    summary: "Public marketing site and pricing for Cander.",
    projectId: "cander",
    workspaceId: "marketing",
    updatedAt: "2h ago",
    published: true,
    image: "/previews/cander.png",
  },
  {
    id: "pv-portal",
    name: "Client Portal",
    summary: "Customer-facing portal for proposals and files.",
    projectId: "client-portal",
    workspaceId: "marketing",
    updatedAt: "3d ago",
    published: true,
    image: "/previews/portal.png",
  },
  {
    id: "pv-launch",
    name: "Launch Site",
    summary: "Campaign landing pages for the next Cander drop.",
    projectId: "launch-site",
    workspaceId: "marketing",
    updatedAt: "5h ago",
    image: "/previews/launch.png",
  },
  {
    id: "pv-cander-pricing",
    name: "Cander Pricing",
    summary: "Plan comparison and checkout, isolated preview.",
    projectId: "cander",
    workspaceId: "marketing",
    updatedAt: "6h ago",
    published: true,
    image: "/previews/pricing.png",
  },
  {
    id: "pv-cander-docs",
    name: "Cander Docs",
    summary: "Product docs attached to the marketing site.",
    projectId: "cander",
    workspaceId: "marketing",
    updatedAt: "1d ago",
    image: "/previews/docs.png",
  },
  {
    id: "pv-portal-staging",
    name: "Portal Staging",
    summary: "Unsigned proposal flow before it goes live.",
    projectId: "client-portal",
    workspaceId: "marketing",
    updatedAt: "4h ago",
    image: "/previews/staging.png",
  },
  {
    id: "pv-crm",
    name: "Field CRM",
    summary: "Jobs, crews, and quotes for landscaping teams.",
    projectId: "field-crm",
    workspaceId: "marketing",
    updatedAt: "6h ago",
    published: true,
    image: "/previews/crm.png",
  },
  {
    id: "pv-console",
    name: "Operator Console",
    summary: "Internal status board for live customer work.",
    projectId: "operator-console",
    workspaceId: "marketing",
    updatedAt: "1d ago",
    image: "/previews/console.png",
  },
  {
    id: "pv-onboarding",
    name: "Onboarding",
    summary: "First-run flow after someone creates an account.",
    projectId: "onboarding",
    workspaceId: "marketing",
    updatedAt: "2d ago",
    image: "/previews/onboarding.png",
  },
  {
    id: "pv-starbase",
    name: "Starbase",
    summary: "Internal operator console for fleet telemetry.",
    projectId: "starbase",
    workspaceId: "engineering",
    updatedAt: "Yesterday",
    published: true,
    image: "/previews/starbase.png",
  },
];

export const scheduledJobs: ScheduledJob[] = [
  {
    id: "job-weekly-cander",
    name: "Cander landing hero",
    workspaceId: "marketing",
    space: "build",
    projectId: "cander",
    threadId: "t-cander-hero",
    snippet: "Tighten the hero and ship a preview every Monday.",
    schedule: "Every Monday 09:00",
    nextRun: "Mon, Aug 17",
    lastRun: "Mon, Aug 10",
    status: "upcoming",
    owner: "Ava Chen",
  },
  {
    id: "job-daily-competitors",
    name: "OpenAI pricing notes",
    workspaceId: "marketing",
    space: "research",
    projectId: "competitor-research",
    threadId: "t-pricing",
    snippet: "Refresh competitor pricing and attach new sources.",
    schedule: "Every day 07:30",
    nextRun: "Tomorrow 07:30",
    lastRun: "Today 07:30",
    status: "active",
    owner: "Sofia Alvarez",
  },
  {
    id: "job-monthly-usage",
    name: "Workspace usage brief",
    workspaceId: "operations",
    space: "research",
    snippet: "Summarize seat and development spend for the workspace.",
    schedule: "1st of each month",
    nextRun: "Sep 1",
    lastRun: "Aug 1",
    status: "paused",
    owner: "Noah Patel",
  },
  {
    id: "job-portal-digest",
    name: "Portal weekly digest",
    workspaceId: "marketing",
    space: "build",
    projectId: "client-portal",
    snippet: "Summarize new proposals and files for the team.",
    schedule: "Every Friday 16:00",
    nextRun: "Fri, Aug 21",
    lastRun: "Fri, Aug 14",
    status: "upcoming",
    owner: "Ava Chen",
  },
  {
    id: "job-seo",
    name: "SEO audit",
    workspaceId: "marketing",
    space: "skills",
    projectId: "cander",
    snippet: "Run the SEO skill on the live marketing site.",
    schedule: "Every Monday 09:00",
    nextRun: "Mon, Aug 17",
    lastRun: "Mon, Aug 10",
    status: "active",
    owner: "Sofia Alvarez",
  },
  {
    id: "job-a11y",
    name: "Accessibility pass",
    workspaceId: "marketing",
    space: "skills",
    projectId: "launch-site",
    snippet: "Scan the launch pages before they go live.",
    schedule: "Every weekday 09:00",
    nextRun: "Tomorrow 09:00",
    lastRun: "Today 09:00",
    status: "paused",
    owner: "Ava Chen",
  },
  {
    id: "job-crm",
    name: "CRM follow-ups",
    workspaceId: "marketing",
    space: "build",
    projectId: "field-crm",
    snippet: "Draft follow-ups for jobs that went quiet.",
    schedule: "Every weekday 09:00",
    nextRun: "Tomorrow 09:00",
    lastRun: "Today 09:00",
    status: "upcoming",
    owner: "Noah Patel",
  },
  {
    id: "job-onboarding",
    name: "Onboarding review",
    workspaceId: "marketing",
    space: "build",
    projectId: "onboarding",
    snippet: "Check the first-run flow after each ship.",
    schedule: "Every Friday 16:00",
    nextRun: "Fri, Aug 21",
    lastRun: "Fri, Aug 14",
    status: "upcoming",
    owner: "Sofia Alvarez",
  },
  {
    id: "job-campaign-stills",
    name: "Campaign stills",
    workspaceId: "marketing",
    space: "studio",
    projectId: "product-campaign",
    snippet: "Generate three stills for the next drop.",
    schedule: "Every Monday 09:00",
    nextRun: "Mon, Aug 17",
    lastRun: "Mon, Aug 10",
    status: "active",
    owner: "Ava Chen",
  },
];

function conn(
  row: Omit<Connector, "scope" | "installed" | "accounts"> & {
    scope?: Connector["scope"];
    installed?: boolean;
    accounts?: ConnectorAccount[];
  },
): Connector {
  return {
    scope: "public",
    installed: false,
    accounts: [],
    ...row,
  };
}

export const connectors: Connector[] = [
  conn({
    id: "handshake",
    name: "Handshake",
    category: "Featured",
    description: "Trust layer between AI agents and your business",
    icon: "handshake",
    featured: true,
    installed: false,
    actions: ["Connect systems", "Manage capabilities", "Review conversations"],
  }),
  conn({
    id: "gmail",
    name: "Gmail",
    category: "Productivity",
    description: "Search, read, draft, and send mail via MCP",
    icon: "gmail",
    featured: true,
    installed: true,
    accounts: [
      { id: "g1", label: "matthew@acme.com", status: "connected" },
      { id: "g2", label: "support@acme.com", status: "connected" },
      { id: "g3", label: "sales@acme.com", status: "needs-reauth" },
    ],
    actions: ["Search", "Read", "Draft", "Send", "Labels", "Filters"],
  }),
  conn({
    id: "slack",
    name: "Slack",
    category: "Productivity",
    description: "Search and post in channels",
    icon: "slack",
    featured: true,
    installed: true,
    accounts: [{ id: "sl1", label: "Acme", status: "connected" }],
    actions: ["Post", "Search", "Channels"],
  }),
  conn({
    id: "github",
    name: "GitHub",
    category: "Engineering",
    description: "Repos, pull requests, and issues",
    icon: "github",
    featured: true,
    installed: true,
    accounts: [{ id: "gh1", label: "acme-inc", status: "connected" }],
    actions: ["Repos", "PRs", "Issues", "Actions"],
  }),
  conn({
    id: "stripe",
    name: "Stripe",
    category: "Commerce",
    description: "Customers, invoices, and balance",
    icon: "stripe",
    featured: true,
    installed: true,
    accounts: [{ id: "s1", label: "Acme Inc. live", status: "connected" }],
    actions: ["Customers", "Invoices", "Subscriptions", "Balance"],
  }),
  conn({
    id: "gcal",
    name: "Google Calendar",
    category: "Productivity",
    description: "List and create events",
    icon: "googlecalendar",
    featured: true,
    installed: true,
    accounts: [{ id: "c1", label: "team@acme.com", status: "connected" }],
    actions: ["List events", "Create", "Update"],
  }),
  conn({
    id: "notion",
    name: "Notion",
    category: "Productivity",
    description: "Search pages and databases",
    icon: "notion",
    featured: true,
    actions: ["Pages", "Search", "Database"],
  }),
  conn({
    id: "linear",
    name: "Linear",
    category: "Engineering",
    description: "Issues, projects, and comments",
    icon: "linear",
    featured: true,
    actions: ["Issues", "Projects", "Comments"],
  }),
  conn({
    id: "figma",
    name: "Figma",
    category: "Productivity",
    description: "Files, comments, and export",
    icon: "figma",
    featured: true,
    actions: ["Files", "Comments", "Export"],
  }),
  conn({
    id: "gdrive",
    name: "Google Drive",
    category: "Productivity",
    description: "Find and open files",
    icon: "gdrive",
    featured: true,
    actions: ["List", "Search", "Open"],
  }),
  conn({
    id: "gdocs",
    name: "Google Docs",
    category: "Productivity",
    description: "Read and draft documents",
    icon: "gdocs",
    featured: true,
    actions: ["Read", "Draft", "Comment"],
  }),
  conn({
    id: "outlook",
    name: "Outlook",
    category: "Productivity",
    description: "Mail and calendar for Microsoft",
    icon: "outlook",
    featured: true,
    actions: ["Send", "Search", "Events"],
  }),
  conn({
    id: "zoom",
    name: "Zoom",
    category: "Communication",
    description: "Meetings and recordings",
    icon: "zoom",
    featured: true,
    actions: ["Meetings", "Recordings"],
  }),
  conn({
    id: "asana",
    name: "Asana",
    category: "Productivity",
    description: "Tasks and project status",
    icon: "asana",
    actions: ["Tasks", "Projects"],
  }),
  conn({
    id: "trello",
    name: "Trello",
    category: "Productivity",
    description: "Boards, cards, and lists",
    icon: "trello",
    actions: ["Boards", "Cards"],
  }),
  conn({
    id: "todoist",
    name: "Todoist",
    category: "Productivity",
    description: "Inbox and recurring tasks",
    icon: "todoist",
    actions: ["Tasks", "Projects"],
  }),
  conn({
    id: "monday",
    name: "Monday",
    category: "Productivity",
    description: "Workboards and updates",
    icon: "monday",
    actions: ["Boards", "Items"],
  }),
  conn({
    id: "clickup",
    name: "ClickUp",
    category: "Productivity",
    description: "Tasks, docs, and goals",
    icon: "clickup",
    actions: ["Tasks", "Docs"],
  }),
  conn({
    id: "calendly",
    name: "Calendly",
    category: "Productivity",
    description: "Scheduling links and events",
    icon: "calendly",
    actions: ["Links", "Events"],
  }),
  conn({
    id: "dropbox",
    name: "Dropbox",
    category: "Productivity",
    description: "List, upload, and share files",
    icon: "dropbox",
    actions: ["List", "Upload", "Share"],
  }),
  conn({
    id: "box",
    name: "Box",
    category: "Productivity",
    description: "Company files and folders",
    icon: "box",
    actions: ["List", "Share"],
  }),
  conn({
    id: "confluence",
    name: "Confluence",
    category: "Productivity",
    description: "Team wiki and pages",
    icon: "confluence",
    actions: ["Pages", "Search"],
  }),
  conn({
    id: "airtable",
    name: "Airtable",
    category: "Productivity",
    description: "Bases, records, and views",
    icon: "airtable",
    actions: ["Bases", "Records"],
  }),
  conn({
    id: "zapier",
    name: "Zapier",
    category: "Productivity",
    description: "Run zaps from chat",
    icon: "zapier",
    actions: ["Zaps", "History"],
  }),
  conn({
    id: "jira",
    name: "Jira",
    category: "Engineering",
    description: "Issues, boards, and sprints",
    icon: "jira",
    actions: ["Issues", "Boards", "Sprint"],
  }),
  conn({
    id: "vercel",
    name: "Vercel",
    category: "Engineering",
    description: "Deploys, domains, and logs",
    icon: "vercel",
    actions: ["Deploy", "Domains", "Logs"],
  }),
  conn({
    id: "cloudflare",
    name: "Cloudflare",
    category: "Engineering",
    description: "Pages, workers, and DNS",
    icon: "cloudflare",
    actions: ["Pages", "Workers", "DNS"],
  }),
  conn({
    id: "sentry",
    name: "Sentry",
    category: "Engineering",
    description: "Errors and release health",
    icon: "sentry",
    actions: ["Issues", "Releases"],
  }),
  conn({
    id: "datadog",
    name: "Datadog",
    category: "Engineering",
    description: "Metrics, logs, and traces",
    icon: "datadog",
    actions: ["Metrics", "Logs"],
  }),
  conn({
    id: "gitlab",
    name: "GitLab",
    category: "Engineering",
    description: "Repos, MRs, and pipelines",
    icon: "gitlab",
    actions: ["Repos", "Merge requests"],
  }),
  conn({
    id: "bitbucket",
    name: "Bitbucket",
    category: "Engineering",
    description: "Repos and pull requests",
    icon: "bitbucket",
    actions: ["Repos", "PRs"],
  }),
  conn({
    id: "webflow",
    name: "Webflow",
    category: "Engineering",
    description: "CMS items and publishes",
    icon: "webflow",
    actions: ["CMS", "Publish"],
  }),
  conn({
    id: "supabase",
    name: "Supabase",
    category: "Data",
    description: "Database, auth, and storage",
    icon: "supabase",
    actions: ["Database", "Auth", "Storage"],
  }),
  conn({
    id: "firebase",
    name: "Firebase",
    category: "Data",
    description: "Auth, database, and hosting",
    icon: "firebase",
    actions: ["Auth", "Database", "Hosting"],
  }),
  conn({
    id: "neon",
    name: "Neon",
    category: "Data",
    description: "Postgres and branches",
    icon: "neon",
    actions: ["Database", "Branches"],
  }),
  conn({
    id: "mixpanel",
    name: "Mixpanel",
    category: "Data",
    description: "Events and funnels",
    icon: "mixpanel",
    actions: ["Events", "Funnels"],
  }),
  conn({
    id: "amplitude",
    name: "Amplitude",
    category: "Data",
    description: "Product analytics charts",
    icon: "amplitude",
    actions: ["Charts", "Cohorts"],
  }),
  conn({
    id: "segment",
    name: "Segment",
    category: "Data",
    description: "Sources and destinations",
    icon: "segment",
    actions: ["Sources", "Events"],
  }),
  conn({
    id: "snowflake",
    name: "Snowflake",
    category: "Data",
    description: "Warehouses and queries",
    icon: "snowflake",
    actions: ["Query", "Tables"],
  }),
  conn({
    id: "bigquery",
    name: "BigQuery",
    category: "Data",
    description: "Run warehouse queries",
    icon: "bigquery",
    actions: ["Query", "Datasets"],
  }),
  conn({
    id: "discord",
    name: "Discord",
    category: "Communication",
    description: "Channels, posts, and search",
    icon: "discord",
    actions: ["Channels", "Post", "Search"],
  }),
  conn({
    id: "teams",
    name: "Microsoft Teams",
    category: "Communication",
    description: "Chats, channels, and meetings",
    icon: "teams",
    actions: ["Chat", "Channels"],
  }),
  conn({
    id: "intercom",
    name: "Intercom",
    category: "Communication",
    description: "Inbox and customer chats",
    icon: "intercom",
    actions: ["Inbox", "Users"],
  }),
  conn({
    id: "twilio",
    name: "Twilio",
    category: "Communication",
    description: "SMS and voice logs",
    icon: "twilio",
    actions: ["SMS", "Calls"],
  }),
  conn({
    id: "front",
    name: "Front",
    category: "Communication",
    description: "Shared inbox threads",
    icon: "front",
    actions: ["Inbox", "Tags"],
  }),
  conn({
    id: "resend",
    name: "Resend",
    category: "Communication",
    description: "Transactional email and domains",
    icon: "resend",
    actions: ["Send", "Domains"],
  }),
  conn({
    id: "hubspot",
    name: "HubSpot",
    category: "Commerce",
    description: "Contacts, deals, and notes",
    icon: "hubspot",
    actions: ["Contacts", "Deals", "Notes"],
  }),
  conn({
    id: "salesforce",
    name: "Salesforce",
    category: "Commerce",
    description: "Accounts, leads, and opportunities",
    icon: "salesforce",
    actions: ["Accounts", "Leads"],
  }),
  conn({
    id: "shopify",
    name: "Shopify",
    category: "Commerce",
    description: "Orders, products, and customers",
    icon: "shopify",
    actions: ["Orders", "Products"],
  }),
  conn({
    id: "customerio",
    name: "Customer.io",
    category: "Commerce",
    description: "Journeys and campaigns",
    icon: "customerio",
    actions: ["Campaigns", "People"],
  }),
  conn({
    id: "clerk",
    name: "Clerk",
    category: "Engineering",
    description: "Users and sessions",
    icon: "clerk",
    actions: ["Users", "Sessions"],
  }),
  conn({
    id: "openai",
    name: "OpenAI",
    category: "Engineering",
    description: "Chat and embeddings",
    icon: "openai",
    actions: ["Chat", "Embeddings"],
  }),
  conn({
    id: "anthropic",
    name: "Anthropic",
    category: "Engineering",
    description: "Claude chat completions",
    icon: "anthropic",
    actions: ["Chat"],
  }),
  conn({
    id: "acme-wiki",
    name: "Acme Wiki",
    category: "Internal",
    description: "Private wiki for this org",
    icon: "notion",
    scope: "personal",
    installed: true,
    accounts: [{ id: "aw1", label: "Acme internal", status: "connected" }],
    actions: ["Search", "Pages"],
  }),
  conn({
    id: "acme-crm",
    name: "Acme CRM",
    category: "Internal",
    description: "Internal accounts and notes",
    icon: "hubspot",
    scope: "personal",
    actions: ["Accounts", "Notes"],
  }),
  conn({
    id: "local-files",
    name: "Local files",
    category: "Internal",
    description: "Folders on this machine",
    icon: "dropbox",
    scope: "personal",
    installed: true,
    accounts: [{ id: "lf1", label: "Matthew’s Mac", status: "connected" }],
    actions: ["List", "Open"],
  }),
  conn({
    id: "team-drive",
    name: "Team Drive",
    category: "Internal",
    description: "Shared marketing assets",
    icon: "gdrive",
    scope: "personal",
    actions: ["List", "Search"],
  }),
  conn({
    id: "custom-mcp",
    name: "Custom MCP",
    category: "Internal",
    description: "A server you added by URL",
    icon: "github",
    scope: "personal",
    actions: ["Tools"],
  }),
  conn({
    id: "stash",
    name: "Stash",
    category: "Internal",
    description: "Private notes Courier can cite",
    icon: "notion",
    scope: "personal",
    actions: ["Notes", "Search"],
  }),
];

export const skills: Skill[] = [
  {
    id: "sk-brand",
    name: "Recursion voice",
    summary: "Keep replies Graphite: short, left-aligned, no hype.",
    when: "Any customer-facing copy",
    workspaceId: "marketing",
    source: "custom",
    updatedAt: "2d ago",
  },
  {
    id: "sk-preview",
    name: "Always attach preview",
    summary: "When building a page, open Preview after the first reply.",
    when: "Build chats",
    workspaceId: "marketing",
    source: "ai",
    updatedAt: "5h ago",
  },
  {
    id: "sk-cite",
    name: "Cite sources",
    summary: "Name the URL next to every claim in Research.",
    when: "Research chats",
    workspaceId: "marketing",
    source: "custom",
    updatedAt: "1w ago",
  },
  {
    id: "sk-seo",
    name: "SEO audit",
    summary: "Check titles, descriptions, and heading order, then apply the easy wins.",
    when: "After a page ships",
    workspaceId: "marketing",
    source: "ai",
    updatedAt: "3h ago",
  },
  {
    id: "sk-a11y",
    name: "Accessibility review",
    summary: "Scan contrast, focus, and alt text without dumping a log.",
    when: "Before publish",
    workspaceId: "marketing",
    source: "custom",
    updatedAt: "1d ago",
  },
  {
    id: "sk-landing",
    name: "Landing page optimization",
    summary: "Tighten the hero, one job per screen, delay the form.",
    when: "Marketing pages",
    workspaceId: "marketing",
    source: "ai",
    updatedAt: "8h ago",
  },
  {
    id: "sk-security",
    name: "Security review",
    summary: "Look for secrets in source, open CORS, and missing auth on routes.",
    when: "Before a deploy",
    workspaceId: "marketing",
    source: "custom",
    updatedAt: "4d ago",
  },
  {
    id: "sk-data",
    name: "Database architecture",
    summary: "Keep tables obvious: who, what, and when — no premature microservices.",
    when: "When adding data",
    workspaceId: "marketing",
    source: "ai",
    updatedAt: "2d ago",
  },
  {
    id: "sk-mobile",
    name: "Mobile responsiveness",
    summary: "Check the page at phone width and fix the three largest breaks.",
    when: "After layout changes",
    workspaceId: "marketing",
    source: "custom",
    updatedAt: "6h ago",
  },
];

export const assetFiles: AssetFile[] = [
  {
    id: "af-hero",
    name: "cander-hero.png",
    kind: "image",
    ext: "PNG",
    size: "1.8 MB",
    source: "studio",
    projectId: "product-campaign",
    workspaceId: "marketing",
    updatedAt: "2h ago",
    cover: "/studio/still.png",
  },
  {
    id: "af-pricing",
    name: "pricing-page.tsx",
    kind: "code",
    ext: "TSX",
    size: "12 KB",
    source: "build",
    projectId: "cander",
    workspaceId: "marketing",
    updatedAt: "2h ago",
  },
  {
    id: "af-brief",
    name: "competitor-brief.pdf",
    kind: "document",
    ext: "PDF",
    size: "420 KB",
    source: "research",
    projectId: "competitor-research",
    workspaceId: "marketing",
    updatedAt: "5h ago",
  },
  {
    id: "af-cutdown",
    name: "launch-cutdown.mp4",
    kind: "media",
    ext: "MP4",
    size: "24 MB",
    source: "studio",
    projectId: "demo-videos",
    workspaceId: "marketing",
    updatedAt: "1d ago",
    cover: "/previews/studio-demo.png",
  },
  {
    id: "af-packshot",
    name: "cander-packshot.png",
    kind: "image",
    ext: "PNG",
    size: "2.4 MB",
    source: "studio",
    projectId: "product-campaign",
    workspaceId: "marketing",
    updatedAt: "6h ago",
    cover: "/studio/retouch.png",
  },
  {
    id: "af-loop",
    name: "hero-loop.mp4",
    kind: "media",
    ext: "MP4",
    size: "18 MB",
    source: "studio",
    projectId: "demo-videos",
    workspaceId: "marketing",
    updatedAt: "2d ago",
    cover: "/studio/video.png",
  },
  {
    id: "af-deck",
    name: "campaign-deck.pdf",
    kind: "document",
    ext: "PDF",
    size: "4.1 MB",
    source: "studio",
    projectId: "product-campaign",
    workspaceId: "marketing",
    updatedAt: "3d ago",
  },
  {
    id: "af-voice",
    name: "recursion-voice.md",
    kind: "document",
    ext: "MD",
    size: "6 KB",
    source: "skills",
    workspaceId: "marketing",
    updatedAt: "2d ago",
  },
  {
    id: "af-matrix",
    name: "feature-matrix.csv",
    kind: "data",
    ext: "CSV",
    size: "22 KB",
    source: "research",
    workspaceId: "marketing",
    updatedAt: "1d ago",
  },
  {
    id: "af-stills",
    name: "spring-stills",
    kind: "folder",
    ext: "Folder",
    size: "8 items",
    source: "studio",
    projectId: "product-campaign",
    workspaceId: "marketing",
    updatedAt: "3d ago",
  },
  {
    id: "af-crm",
    name: "field-crm-schema.sql",
    kind: "code",
    ext: "SQL",
    size: "9 KB",
    source: "build",
    projectId: "field-crm",
    workspaceId: "marketing",
    updatedAt: "4d ago",
  },
  {
    id: "af-press",
    name: "press-kit.pdf",
    kind: "document",
    ext: "PDF",
    size: "2.2 MB",
    source: "research",
    workspaceId: "marketing",
    updatedAt: "1w ago",
  },
];

export const starterThreads: Thread[] = [
  {
    id: "t-work-inbox",
    title: "Inbox for today",
    workspaceId: "marketing",
    projectId: "today-inbox",
    spaceId: "work",
    updatedAt: "1h ago",
    snippet: "Summarize everything I need to respond to today.",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Summarize everything I need to respond to today.",
        at: "9:12",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Opened Work on today’s inbox. Two Slack threads and Northwind’s pricing note are waiting — say which to draft first.",
        at: "9:12",
      },
    ],
  },
  {
    id: "t-cander-hero",
    title: "Cander landing hero",
    workspaceId: "marketing",
    projectId: "cander",
    spaceId: "build",
    updatedAt: "2h ago",
    snippet: "Tighten the hero and ship a preview.",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Build me a landing page for Cander.",
        at: "12:04",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Opened Build on Cander. Preview is on the right — hero, pricing, and footer. Say what to change.",
        at: "12:04",
      },
    ],
  },
  {
    id: "t-campaign",
    title: "Product photo retouch",
    workspaceId: "marketing",
    projectId: "product-campaign",
    spaceId: "studio",
    updatedAt: "4h ago",
    snippet: "Remove background on the stills.",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Edit this photo and remove the background.",
        at: "10:18",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Studio is open on Product Campaign. Background removal is queued on shot 03. Canvas is on the right.",
        at: "10:18",
      },
    ],
  },
  {
    id: "t-pricing",
    title: "OpenAI pricing vs Cander",
    workspaceId: "marketing",
    projectId: "cander",
    spaceId: "research",
    updatedAt: "Yesterday",
    snippet: "Update Cander pricing from the research notes.",
    shared: true,
    messages: [
      {
        id: "m1",
        role: "user",
        content:
          "Research OpenAI pricing and update the pricing section of the Cander website.",
        at: "Yesterday",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "This belongs to Cander. I pulled competitor pricing into Research, then opened the Cander pricing page in Build. Both stay attached to the same project.",
        at: "Yesterday",
      },
    ],
  },
  {
    id: "t-portal",
    title: "Client portal files view",
    workspaceId: "marketing",
    projectId: "client-portal",
    spaceId: "build",
    updatedAt: "3d ago",
    snippet: "Add a files tab to the portal.",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Add a files section to the client portal.",
        at: "Mon 14:02",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Opened Build on Client Portal. Files tab is in the preview — upload list, empty state, and detail drawer.",
        at: "Mon 14:02",
      },
    ],
  },
  {
    id: "t-demo",
    title: "Cander demo cutdown",
    workspaceId: "marketing",
    projectId: "demo-videos",
    spaceId: "studio",
    updatedAt: "1d ago",
    snippet: "30s walkthrough from the hero stills.",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Turn the hero stills into a 30-second product demo.",
        at: "Mon 11:40",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Studio is open on Demo Videos. Text-to-video is queued — canvas shows the storyboard on the right.",
        at: "Mon 11:40",
      },
    ],
  },
  {
    id: "t-competitors",
    title: "Competitor Research",
    workspaceId: "marketing",
    projectId: "competitor-research",
    spaceId: "research",
    updatedAt: "5h ago",
    snippet: "Cursor, Lovable, and pricing clusters.",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Research these competitors.",
        at: "08:12",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Research is open on Competitor Research. 37 sources saved — pricing and positioning notes are on the page.",
        at: "08:12",
      },
    ],
  },
  {
    id: "t-pricing-landscape",
    title: "Pricing Landscape",
    workspaceId: "marketing",
    projectId: "pricing-landscape",
    spaceId: "research",
    updatedAt: "8h ago",
    snippet: "Seat vs token models across the category.",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Map seat vs token billing across AI dev tools.",
        at: "07:45",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Added 14 sources to Pricing Landscape. Comparison table and citations are attached to the paper.",
        at: "07:45",
      },
    ],
  },
  {
    id: "t-skill-voice",
    title: "Recursion voice skill",
    workspaceId: "marketing",
    spaceId: "skills",
    updatedAt: "5h ago",
    snippet: "Keep replies Graphite: short, left-aligned, no hype.",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Write a skill for Recursion tone of voice.",
        at: "09:12",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Drafted Recursion voice. Name, when-to-use, and instructions are on the right — edit them, then save.",
        at: "09:12",
      },
    ],
  },
  {
    id: "t-plat-keys",
    title: "Rotate production keys",
    workspaceId: "marketing",
    product: "platform",
    platformNav: "keys",
    updatedAt: "2h ago",
    snippet: "Where do I rotate API keys?",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Where do I rotate API keys?",
        at: "11:04",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Opened Keys. Create and rotate credentials here — keep them out of source.",
        at: "11:04",
      },
    ],
  },
  {
    id: "t-plat-hosting",
    title: "Cloud vs on-device",
    workspaceId: "marketing",
    product: "platform",
    platformNav: "hosting",
    updatedAt: "Yesterday",
    snippet: "Which hosting model should we use?",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Which hosting model should we use?",
        at: "16:22",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Opened Hosting. Cloud, local, and on-device are the same product with different runtimes.",
        at: "16:22",
      },
    ],
  },
  {
    id: "t-plat-models",
    title: "On-device Gemma 4",
    workspaceId: "engineering",
    product: "platform",
    platformNav: "models",
    updatedAt: "2d ago",
    snippet: "What’s running on-device right now?",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "What’s running on-device right now?",
        at: "08:10",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Opened Models. Cloud, local, and on-device runtimes are listed with memory and status.",
        at: "08:10",
      },
    ],
  },
  {
    id: "t-plat-usage",
    title: "This month’s API spend",
    workspaceId: "marketing",
    product: "platform",
    platformNav: "usage",
    updatedAt: "3d ago",
    snippet: "Show me usage and billing for APIs.",
    messages: [
      {
        id: "m1",
        role: "user",
        content: "Show me usage and billing for APIs.",
        at: "14:41",
      },
      {
        id: "m2",
        role: "assistant",
        content:
          "Opened Usage. Requests, spend, and plan limits for this workspace are on this page.",
        at: "14:41",
      },
    ],
  },
];

export const canderFiles = [
  { path: "app/page.tsx", kind: "file" as const },
  { path: "app/pricing/page.tsx", kind: "file" as const },
  { path: "components/Hero.tsx", kind: "file" as const },
  { path: "components/Pricing.tsx", kind: "file" as const, active: true },
  { path: "lib/plans.ts", kind: "file" as const },
];

export const canderCode = `export function Pricing() {
  return (
    <section className="mx-auto max-w-5xl px-6 py-24">
      <p className="text-sm text-zinc-500">Plans</p>
      <h2 className="mt-2 text-3xl tracking-tight">
        Simple pricing for Cander.
      </h2>
      <div className="mt-10 grid gap-4 md:grid-cols-3">
        <Plan name="Start" price="$29" />
        <Plan name="Studio" price="$79" featured />
        <Plan name="Scale" price="$240" />
      </div>
    </section>
  );
}`;

export const starbaseFiles = [
  { path: "apps/console/page.tsx", kind: "file" as const, active: true },
  { path: "apps/api/routes.ts", kind: "file" as const },
  { path: "infra/compose.yml", kind: "file" as const },
];

export const researchSources = [
  { title: "OpenAI API Pricing", url: "openai.com/api/pricing", tag: "Saved" },
  { title: "Anthropic plans", url: "anthropic.com/pricing", tag: "Saved" },
  { title: "Courier vs token meters", url: "thinkrecursion.ai", tag: "Internal" },
];

export const platformModels = [
  { name: "Gemma 4-e4b", runtime: "On-device", memory: "7.2 GB", status: "Ready" },
  { name: "Gemma 4 E2B", runtime: "Local", memory: "4.1 GB", status: "Ready" },
  { name: "EXAONE 4.0 32B", runtime: "Cloud", memory: "Hosted", status: "Live" },
  { name: "Llama 4 Scout", runtime: "Cloud", memory: "Hosted", status: "Live" },
  { name: "Qwen 3 32B", runtime: "Local", memory: "18 GB", status: "Ready" },
  { name: "Mistral Small", runtime: "Cloud", memory: "Hosted", status: "Live" },
  { name: "Phi-4 Mini", runtime: "On-device", memory: "3.8 GB", status: "Ready" },
  { name: "DeepSeek V3", runtime: "Cloud", memory: "Hosted", status: "Live" },
  { name: "Gemma 4 27B", runtime: "Local", memory: "16 GB", status: "Warm" },
  { name: "Claude-compatible", runtime: "Cloud", memory: "Routed", status: "Live" },
  { name: "Whisper Large", runtime: "Local", memory: "2.9 GB", status: "Ready" },
  { name: "Embedding 3", runtime: "Cloud", memory: "Hosted", status: "Live" },
];

export const platformApis = [
  { id: "chat", name: "Chat completions", path: "/v1/chat/completions", method: "POST" },
  { id: "embeddings", name: "Embeddings", path: "/v1/embeddings", method: "POST" },
  { id: "images", name: "Images", path: "/v1/images/generations", method: "POST" },
  { id: "audio", name: "Audio", path: "/v1/audio/transcriptions", method: "POST" },
  { id: "tools", name: "Tools", path: "/v1/tools", method: "POST" },
  { id: "files", name: "Files", path: "/v1/files", method: "POST" },
  { id: "models", name: "Models", path: "/v1/models", method: "GET" },
  { id: "batches", name: "Batches", path: "/v1/batches", method: "POST" },
];

export const apiKeys = [
  { name: "Production", hint: "crr_live_••••k2a9", created: "Jul 12" },
  { name: "Staging", hint: "crr_test_••••91qx", created: "Aug 2" },
  { name: "CI", hint: "crr_ci_••••4n0w", created: "Aug 8" },
  { name: "Mobile", hint: "crr_app_••••m8kx", created: "Jul 28" },
  { name: "Research", hint: "crr_lab_••••p2r1", created: "Jun 19" },
  { name: "Preview", hint: "crr_prev_••••9q3c", created: "Aug 14" },
];

export const platformDeployments: PlatformDeployment[] = [
  { name: "Cloud · us-east-1", status: "Active", hint: "Primary", hosting: "cloud" },
  { name: "Cloud · eu-west-1", status: "Standby", hint: "Failover", hosting: "cloud" },
  { name: "Local · office LAN", status: "Standby", hint: "Engineering", hosting: "local" },
  { name: "On-device · this Mac", status: "Ready", hint: "Personal", hosting: "on-device" },
  { name: "On-device · fleet", status: "Ready", hint: "12 machines", hosting: "on-device" },
  { name: "Preview · staging", status: "Active", hint: "API sandbox", hosting: "cloud" },
];

export const platformDocs = [
  { title: "TypeScript SDK", body: "npm i @courier/sdk", kind: "SDK" },
  { title: "Python SDK", body: "pip install courier", kind: "SDK" },
  { title: "Go SDK", body: "go get github.com/courier/sdk", kind: "SDK" },
  { title: "Swift SDK", body: "https://github.com/courier/swift", kind: "SDK" },
  { title: "REST gateway", body: "OpenAI-compatible /v1", kind: "Docs" },
  { title: "Streaming", body: "SSE and chunked tokens", kind: "Docs" },
  { title: "Auth", body: "Bearer keys and org scopes", kind: "Docs" },
  { title: "Webhooks", body: "Sign and retry events", kind: "Docs" },
  { title: "On-device runtime", body: "Gemma on this machine", kind: "Docs" },
  { title: "Local LAN", body: "Point clients at the office box", kind: "Docs" },
  { title: "Embeddings", body: "Batch and query vectors", kind: "Docs" },
  { title: "Tools", body: "Function calling and MCP", kind: "Docs" },
];

export const prompts: { id: string; label: string; space: SpaceId }[] = [
  {
    id: "p0",
    label: "Summarize everything I need to respond to today.",
    space: "work",
  },
  { id: "p1", label: "Build me a CRM for landscaping companies.", space: "build" },
  {
    id: "p2",
    label: "Edit this photo and remove the background.",
    space: "studio",
  },
  { id: "p3", label: "Research these competitors.", space: "research" },
  { id: "p4", label: "Write a skill for Recursion tone of voice.", space: "skills" },
  { id: "p5", label: "Turn this still into an 8-second clip.", space: "studio" },
  { id: "p6", label: "Summarize this month’s invoices and what’s still unpaid.", space: "finances" },
  { id: "p7", label: "Draft a care-plan recap from last quarter’s notes.", space: "health" },
];

export const researchPaperPreviews: Record<
  string,
  { title: string; lines: string[] }
> = {
  "competitor-research": {
    title: "Competitor landscape",
    lines: [
      "Cursor leads on IDE-native agents; Lovable on speed-to-preview.",
      "Seat pricing clusters at $20–40; usage tiers emerging fast.",
    ],
  },
  "pricing-landscape": {
    title: "Pricing models",
    lines: [
      "Per-seat vs token hybrid is becoming the category default.",
      "Enterprise quotes still anchor on seats plus premium support.",
    ],
  },
  "voice-of-customer": {
    title: "Customer themes",
    lines: [
      "Teams want preview-first workflows, not repo setup.",
      "Support volume spikes after pricing page changes.",
    ],
  },
  "launch-coverage": {
    title: "Launch coverage",
    lines: [
      "Product Hunt drove 42% of first-week signups for Cander.",
      "Partner newsletters outperformed paid social by 3×.",
    ],
  },
  "channel-mix": {
    title: "Channel mix",
    lines: [
      "Organic search is 38% of qualified inbound this quarter.",
      "Referrals from existing customers grew 12% week over week.",
    ],
  },
  "ai-infrastructure": {
    title: "AI infrastructure",
    lines: [
      "Inference costs drop when caching tool results per session.",
      "Multi-model routing saves ~18% on long research jobs.",
    ],
  },
};

export const recentsStats = {
  stats: [
    { label: "Chats", value: "12" },
    { label: "Projects", value: "8" },
    { label: "Pinned", value: "3" },
    { label: "This week", value: "6", delta: "+2" },
  ],
};

export const spaceStats: Record<
  SpaceId,
  {
    kicker: string;
    stats: { label: string; value: string; delta?: string }[];
  }
> = {
  work: {
    kicker: "Today, follow-ups, approvals",
    stats: [
      { label: "Needs a reply", value: "5" },
      { label: "Meetings today", value: "2" },
      { label: "Follow-ups", value: "4" },
      { label: "Approvals", value: "3" },
    ],
  },
  build: {
    kicker: "Software, sites, and agents",
    stats: [
      { label: "Projects", value: "3" },
      { label: "Previews", value: "11" },
      { label: "Deploys", value: "2" },
      { label: "Open PRs", value: "4" },
    ],
  },
  studio: {
    kicker: "Photos, video, and files",
    stats: [
      { label: "Projects", value: "2" },
      { label: "Photos", value: "2" },
      { label: "Videos", value: "2" },
      { label: "Files", value: "2" },
    ],
  },
  research: {
    kicker: "Sources, notes, reports",
    stats: [
      { label: "Sources", value: "37", delta: "+5 this week" },
      { label: "Notes", value: "18" },
      { label: "Reports", value: "5" },
      { label: "Citations", value: "112", delta: "+14" },
    ],
  },
  files: {
    kicker: "Everything Courier made",
    stats: [
      { label: "Files", value: "9" },
      { label: "Images", value: "1" },
      { label: "Documents", value: "3" },
      { label: "From Studio", value: "3" },
    ],
  },
  skills: {
    kicker: "Reusable instructions",
    stats: [
      { label: "Tasks", value: "9" },
      { label: "AI drafted", value: "4" },
      { label: "Used today", value: "8" },
      { label: "Chats", value: "1" },
    ],
  },
  scheduled: {
    kicker: "Anything that runs later",
    stats: [
      { label: "Upcoming", value: "2" },
      { label: "Active", value: "1" },
      { label: "Paused", value: "1" },
      { label: "Failed", value: "0" },
    ],
  },
  connectors: {
    kicker: "Work with Courier across your tools",
    stats: [
      { label: "Installed", value: "5" },
      { label: "Available", value: "7" },
      { label: "Accounts", value: "8" },
      { label: "Needs reauth", value: "1" },
    ],
  },
  finances: {
    kicker: "Books, invoices, and spend",
    stats: [
      { label: "Open invoices", value: "6" },
      { label: "Spend MTD", value: "$18.4k" },
      { label: "Runway", value: "14 mo" },
      { label: "Needs review", value: "3" },
    ],
  },
  health: {
    kicker: "Care, benefits, and follow-ups",
    stats: [
      { label: "Open items", value: "4" },
      { label: "Care plans", value: "2" },
      { label: "Benefits", value: "1" },
      { label: "Due this week", value: "2" },
    ],
  },
  personal: {
    kicker: "Life outside the product",
    stats: [
      { label: "Today", value: "3" },
      { label: "Goals", value: "4" },
      { label: "Car", value: "2" },
      { label: "Due this week", value: "5" },
    ],
  },
};
