import type { DiscoveryItem } from "./discovery-types";

const item = (row: DiscoveryItem): DiscoveryItem => row;

/** Mock discovery catalog — outcome-first copy, connectors + capabilities. */
export const discoveryCatalog: DiscoveryItem[] = [
  item({
    id: "connect-gmail",
    category: "connector",
    sections: ["recommended", "connect", "get-things-done"],
    title: "Connect Gmail to Courier",
    shortLabel: "Connect Gmail to Courier",
    description:
      "Search, draft, and follow up on email from chat — Courier keeps context with the rest of your work.",
    icon: "gmail",
    iconKind: "connector",
    priority: 96,
    tags: ["email", "inbox", "gmail", "mail"],
    badge: "Recommended",
    requiredConnector: "gmail",
    completionKey: "connector:gmail",
    cta: { kind: "openConnector", target: "gmail", label: "Connect" },
    steps: [
      {
        title: "Bring your inbox into Courier",
        body: "Once Gmail is connected, you can ask Courier to summarize, draft, and follow up without switching tabs.",
      },
      {
        title: "Connect Gmail",
        body: "Authorize the accounts you want Courier to use. You can add more later.",
        action: { kind: "openConnector", target: "gmail", label: "Connect Gmail" },
      },
      {
        title: "Try it",
        body: "Ask Courier to summarize unread mail or draft a reply.",
        action: {
          kind: "prompt",
          target: "Summarize my unread Gmail from today.",
          label: "Try it",
        },
      },
    ],
  }),
  item({
    id: "connect-calendar",
    category: "connector",
    sections: ["recommended", "connect", "get-things-done"],
    title: "Let Courier understand your schedule",
    shortLabel: "Connect your calendar",
    description:
      "Connect Google Calendar so Courier can prepare you for meetings with context from mail, files, and chats.",
    icon: "calendar",
    iconKind: "lucide",
    priority: 94,
    tags: ["meetings", "calendar", "schedule", "prep"],
    badge: "Useful with Work",
    requiredConnector: "gcal",
    completionKey: "connector:gcal",
    cta: { kind: "openSpace", target: "connectors", label: "Connect" },
    examplePrompt: "Prepare me for my next meeting.",
    steps: [
      {
        title: "Courier can prepare you for meetings",
        body: "With calendar and email connected, Courier pulls schedule, conversations, and files before you walk in.",
      },
      {
        title: "Connect Calendar",
        body: "Open Connectors and link Google Calendar (or your preferred calendar).",
        action: { kind: "openSpace", target: "connectors", label: "Open Connectors" },
      },
      {
        title: "Ask for a briefing",
        body: "Try: “Prepare me for my next meeting.”",
        action: {
          kind: "prompt",
          target: "Prepare me for my next meeting.",
          label: "Try it",
        },
      },
    ],
  }),
  item({
    id: "connect-slack",
    category: "connector",
    sections: ["recommended", "connect"],
    title: "Bring Slack into the same thread",
    shortLabel: "Connect Slack to Courier",
    description:
      "Search channels, draft replies, and keep team context next to your projects.",
    icon: "slack",
    iconKind: "connector",
    priority: 88,
    tags: ["slack", "chat", "team"],
    requiredConnector: "slack",
    completionKey: "connector:slack",
    cta: { kind: "openConnector", target: "slack", label: "Connect" },
  }),
  item({
    id: "meeting-prep",
    category: "workflow",
    sections: ["recommended", "get-things-done", "automate"],
    title: "Courier can prepare you for meetings",
    shortLabel: "Courier can prepare meetings",
    description:
      "Connect calendar and email and Courier can pull together your schedule, relevant conversations, files, and context before a meeting.",
    icon: "calendar",
    iconKind: "lucide",
    priority: 86,
    tags: ["meetings", "prep", "calendar", "email"],
    badge: "Try this",
    cta: { kind: "prompt", target: "Prepare me for my next meeting.", label: "Set it up" },
    steps: [
      {
        title: "Meeting prep from chat",
        body: "Courier can assemble agenda, prior notes, and open loops before each meeting.",
      },
      {
        title: "Connect what you already use",
        body: "Calendar and email make prep much stronger. Connect them when you’re ready.",
        action: { kind: "openSpace", target: "connectors", label: "Connect apps" },
      },
      {
        title: "Ask Courier",
        body: "Say “Prepare me for my next meeting” anytime.",
        action: {
          kind: "prompt",
          target: "Prepare me for my next meeting.",
          label: "Try it",
        },
      },
    ],
  }),
  item({
    id: "morning-inbox",
    category: "workflow",
    sections: ["get-things-done", "automate"],
    title: "Summarize my inbox each morning",
    shortLabel: "Morning inbox summary",
    description:
      "Have Courier scan unread mail and surface what needs a reply before your day starts.",
    icon: "mail",
    iconKind: "lucide",
    priority: 78,
    tags: ["email", "inbox", "morning", "summary"],
    cta: {
      kind: "prompt",
      target: "Summarize my unread inbox and flag anything that needs a reply.",
      label: "Try it",
    },
  }),
  item({
    id: "follow-up-email",
    category: "automation",
    sections: ["get-things-done", "automate"],
    title: "Follow up on unanswered emails",
    shortLabel: "Follow up automatically",
    description:
      "Ask Courier to find threads waiting on a reply and draft polite follow-ups.",
    icon: "mail",
    iconKind: "lucide",
    priority: 74,
    tags: ["email", "follow-up", "automation"],
    cta: {
      kind: "prompt",
      target: "Find emails that need a follow-up and draft replies.",
      label: "Try it",
    },
  }),
  item({
    id: "scheduled-tasks",
    category: "automation",
    sections: ["recommended", "automate", "explore"],
    title: "Have Courier do something every morning",
    shortLabel: "Schedule recurring tasks",
    description:
      "Schedule briefings, reports, and reminders so Courier runs work on a cadence you choose.",
    icon: "clock",
    iconKind: "lucide",
    priority: 82,
    tags: ["schedule", "automation", "tasks", "recurring"],
    badge: "Useful with Build",
    requiredSpace: "build",
    cta: { kind: "openSpace", target: "build", label: "Explore" },
    steps: [
      {
        title: "Scheduled work, not one-off chats",
        body: "Courier can run the same job daily or weekly — briefings, summaries, reminders.",
      },
      {
        title: "See examples in Build",
        body: "Open Build → Automations to browse recurring jobs.",
        action: { kind: "openSpace", target: "build", label: "Open Build" },
      },
      {
        title: "Create one from chat",
        body: "Ask Courier to schedule a morning briefing for you.",
        action: {
          kind: "prompt",
          target: "Schedule a daily morning briefing at 8am.",
          label: "Create one",
        },
      },
    ],
  }),
  item({
    id: "build-from-chat",
    category: "space",
    sections: ["recommended", "explore", "get-things-done"],
    title: "Build apps from chat",
    shortLabel: "Build apps from chat",
    description:
      "Describe what you want and Courier scaffolds apps, sites, and automations in Build.",
    icon: "hammer",
    iconKind: "lucide",
    priority: 80,
    tags: ["build", "apps", "website", "ship"],
    requiredSpace: "build",
    completionKey: "space:build",
    cta: { kind: "openSpace", target: "build", label: "Open Build" },
    steps: [
      {
        title: "Ship from conversation",
        body: "Build turns natural language into working software with a live preview.",
      },
      {
        title: "See what people make",
        body: "Browse projects and one-off tasks in Build.",
        action: { kind: "openSpace", target: "build", label: "Open Build" },
      },
      {
        title: "Start building",
        body: "Tell Courier what to create.",
        action: {
          kind: "prompt",
          target: "Build a simple landing page for my product.",
          label: "Start building",
        },
      },
    ],
  }),
  item({
    id: "studio-images",
    category: "space",
    sections: ["explore", "get-things-done"],
    title: "Create images in Studio",
    shortLabel: "Create images in Studio",
    description:
      "Generate stills, edits, and creative assets without leaving Courier.",
    icon: "image",
    iconKind: "lucide",
    priority: 72,
    tags: ["studio", "images", "creative", "design"],
    requiredSpace: "studio",
    completionKey: "space:studio",
    cta: { kind: "openSpace", target: "studio", label: "Open Studio" },
  }),
  item({
    id: "research-cited",
    category: "space",
    sections: ["explore", "get-things-done"],
    title: "Research anything and get cited answers",
    shortLabel: "Research with citations",
    description:
      "Use Research for sources, notes, and cited findings you can reuse in Work or Studio.",
    icon: "telescope",
    iconKind: "lucide",
    priority: 76,
    tags: ["research", "citations", "papers", "competitors"],
    requiredSpace: "research",
    completionKey: "space:research",
    cta: { kind: "openSpace", target: "research", label: "Explore" },
    examplePrompt: "Research competitors in my space and cite sources.",
  }),
  item({
    id: "browse-web",
    category: "feature",
    sections: ["recommended", "explore"],
    title: "Browse the web with Courier",
    shortLabel: "Browse the web with Courier",
    description:
      "Open pages beside chat, attach references, and keep browsing context in the thread.",
    icon: "globe",
    iconKind: "lucide",
    priority: 84,
    tags: ["browser", "web", "browse", "pages"],
    completionKey: "feature:browser",
    cta: { kind: "openBrowser", label: "Show me" },
  }),
  item({
    id: "voice",
    category: "feature",
    sections: ["explore"],
    title: "Talk to Courier with voice",
    shortLabel: "Use voice with Courier",
    description:
      "Hands-free prompts and replies when you’re away from the keyboard.",
    icon: "mic",
    iconKind: "lucide",
    priority: 58,
    tags: ["voice", "mic", "hands-free"],
    badge: "Advanced",
    cta: { kind: "openDiscovery", label: "Learn more" },
  }),
  item({
    id: "work-space",
    category: "space",
    sections: ["explore", "recommended"],
    title: "Keep work moving from one inbox",
    shortLabel: "Open Work for today",
    description:
      "Work brings mail, follow-ups, approvals, and customers into one operational surface.",
    icon: "briefcase",
    iconKind: "lucide",
    priority: 70,
    tags: ["work", "inbox", "customers"],
    requiredSpace: "work",
    completionKey: "space:work",
    cta: { kind: "openSpace", target: "work", label: "Open Work" },
  }),
  item({
    id: "personal-space",
    category: "space",
    sections: ["explore"],
    title: "Keep personal life in its own space",
    shortLabel: "Explore Personal space",
    description:
      "Finances, health, goals, and life admin — separate from team Work when you want privacy.",
    icon: "user",
    iconKind: "lucide",
    priority: 55,
    tags: ["personal", "life", "health", "finances"],
    requiredSpace: "personal",
    completionKey: "space:personal",
    cta: { kind: "openSpace", target: "personal", label: "Explore" },
  }),
  item({
    id: "share-workspace",
    category: "collaboration",
    sections: ["explore"],
    title: "Share a workspace with your team",
    shortLabel: "Share a workspace",
    description:
      "Invite people, control spaces, and keep knowledge bases on the workspace.",
    icon: "users",
    iconKind: "lucide",
    priority: 62,
    tags: ["workspace", "share", "team", "invite"],
    badge: "Collaboration",
    cta: { kind: "openDiscovery", label: "Show me" },
  }),
  item({
    id: "local-ai",
    category: "hosting",
    sections: ["private-ai", "explore"],
    title: "Run AI on your device",
    shortLabel: "Run AI on your device",
    description:
      "Host models locally when you want inference on hardware you control.",
    icon: "cpu",
    iconKind: "lucide",
    priority: 68,
    tags: ["local", "hosting", "private", "on-device", "offline"],
    badge: "Private AI",
    cta: { kind: "openPlatform", target: "hosting", label: "Open Hosting" },
    steps: [
      {
        title: "Your hardware, your inference",
        body: "Courier can run models on devices you own — cloud stays a choice.",
      },
      {
        title: "Why teams use local",
        body: "Keep sensitive work off the public cloud while still using the same Courier interface.",
      },
      {
        title: "Open Hosting",
        body: "Development → Hosting walks through cloud, local, and on-device options.",
        action: { kind: "openPlatform", target: "hosting", label: "Open Hosting" },
      },
    ],
  }),
  item({
    id: "apis-keys",
    category: "development",
    sections: ["explore", "private-ai"],
    title: "Call Courier from your own stack",
    shortLabel: "Use APIs and keys",
    description:
      "Generate keys and use OpenAI-compatible APIs from apps you already ship.",
    icon: "key",
    iconKind: "lucide",
    priority: 60,
    tags: ["api", "keys", "developers", "integration"],
    badge: "Development",
    cta: { kind: "openPlatform", target: "api", label: "Open APIs" },
  }),
  item({
    id: "notes-to-deck",
    category: "workflow",
    sections: ["get-things-done"],
    title: "Turn notes into a presentation",
    shortLabel: "Notes into a presentation",
    description:
      "Drop rough notes and ask Courier to structure slides or a Studio brief.",
    icon: "presentation",
    iconKind: "lucide",
    priority: 64,
    tags: ["presentation", "notes", "studio", "slides"],
    cta: {
      kind: "prompt",
      target: "Turn these notes into a short presentation outline.",
      label: "Try it",
    },
  }),
  item({
    id: "competitor-research",
    category: "workflow",
    sections: ["get-things-done"],
    title: "Research competitors with sources",
    shortLabel: "Research competitors",
    description:
      "Open Research and ask for a cited landscape of competitors and positioning.",
    icon: "telescope",
    iconKind: "lucide",
    priority: 66,
    tags: ["research", "competitors", "market"],
    cta: {
      kind: "prompt",
      target: "Research my top competitors and cite sources.",
      label: "Try it",
    },
  }),
  item({
    id: "publish-site",
    category: "workflow",
    sections: ["get-things-done", "explore"],
    title: "Build and publish a website",
    shortLabel: "Build and publish a site",
    description:
      "Scaffold in Build, refine in preview, then publish when it’s ready.",
    icon: "hammer",
    iconKind: "lucide",
    priority: 71,
    tags: ["build", "website", "publish"],
    cta: {
      kind: "prompt",
      target: "Build a simple marketing site I can publish.",
      label: "Start building",
    },
  }),
  item({
    id: "social-content",
    category: "workflow",
    sections: ["get-things-done"],
    title: "Generate social content",
    shortLabel: "Generate social content",
    description:
      "Draft posts and visuals from a brief using Studio and chat together.",
    icon: "image",
    iconKind: "lucide",
    priority: 57,
    tags: ["social", "content", "studio", "marketing"],
    cta: {
      kind: "prompt",
      target: "Draft three social posts and a visual concept for our launch.",
      label: "Try it",
    },
  }),
  item({
    id: "daily-briefing",
    category: "automation",
    sections: ["automate"],
    title: "Get a daily briefing",
    shortLabel: "Daily briefing automation",
    description:
      "Schedule a morning digest of calendar, mail, and open work.",
    icon: "clock",
    iconKind: "lucide",
    priority: 73,
    tags: ["briefing", "daily", "automation", "morning"],
    cta: {
      kind: "prompt",
      target: "Set up a daily morning briefing for me.",
      label: "Set it up",
    },
  }),
  item({
    id: "keyboard-search",
    category: "tip",
    sections: ["explore"],
    title: "Jump anywhere with search",
    shortLabel: "Use ⌘K to search",
    description:
      "Press ⌘K (Ctrl+K) to open search and jump to spaces, chats, and actions.",
    icon: "search",
    iconKind: "lucide",
    priority: 48,
    tags: ["keyboard", "shortcut", "search"],
    badge: "Tip",
    cta: { kind: "openDiscovery", label: "Got it" },
  }),
  item({
    id: "memory-context",
    category: "feature",
    sections: ["explore"],
    title: "Courier keeps context across chats",
    shortLabel: "Persistent context cues",
    description:
      "Space chats resume where you left off, with session summaries when you close the dock.",
    icon: "sparkles",
    iconKind: "lucide",
    priority: 52,
    tags: ["memory", "context", "persistent", "chat"],
    cta: { kind: "newChat", label: "Open a chat" },
  }),
];

export function discoveryItemById(id: string) {
  return discoveryCatalog.find((item) => item.id === id) ?? null;
}
