#!/usr/bin/env bash
# Write .env.local from Cloud Agent / shell secrets (never commit this file).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env.local"

url="${NEXT_PUBLIC_SUPABASE_URL:-}"
anon="${NEXT_PUBLIC_SUPABASE_ANON_KEY:-}"
service="${SUPABASE_SERVICE_ROLE_KEY:-}"

if [[ -z "$url" || -z "$anon" ]]; then
  echo "Missing NEXT_PUBLIC_SUPABASE_URL and/or NEXT_PUBLIC_SUPABASE_ANON_KEY in the environment." >&2
  echo "Add them to Cloud Agent secrets or export them, then rerun: bash scripts/sync-env-local.sh" >&2
  exit 1
fi

cat >"$ENV_FILE" <<EOF
# Generated by scripts/sync-env-local.sh — do not commit
NEXT_PUBLIC_SUPABASE_URL=$url
NEXT_PUBLIC_SUPABASE_ANON_KEY=$anon
NEXT_PUBLIC_DATA_BACKEND=supabase
EOF

if [[ -n "$service" ]]; then
  echo "SUPABASE_SERVICE_ROLE_KEY=$service" >>"$ENV_FILE"
fi

echo "Wrote $ENV_FILE (Supabase URL + anon key). Restart npm run dev if it is already running."
