-- Enable non-Google app connectors for Composio OAuth.
-- Shopify stays coming_soon until custom OAuth credentials are configured.

insert into public.connector_catalog
  (id, name, category, description, icon, scope, featured, actions, panel_type,
   display_order, enabled, coming_soon, provider_toolkit_id)
values
  (
    'outlook',
    'Outlook',
    'Communication',
    'Mail, calendar, and contacts for Microsoft 365',
    'outlook',
    'public',
    true,
    '["Inbox","Calendar","Contacts"]'::jsonb,
    'generic',
    20,
    true,
    false,
    'outlook'
  ),
  (
    'slack',
    'Slack',
    'Communication',
    'Search and post in channels',
    'slack',
    'public',
    true,
    '["Channels","Search","Post"]'::jsonb,
    'generic',
    21,
    true,
    false,
    'slack'
  ),
  (
    'notion',
    'Notion',
    'Productivity',
    'Search pages and databases',
    'notion',
    'public',
    true,
    '["Pages","Search","Database"]'::jsonb,
    'generic',
    22,
    true,
    false,
    'notion'
  ),
  (
    'hubspot',
    'HubSpot',
    'Commerce',
    'Contacts, deals, and companies',
    'hubspot',
    'public',
    true,
    '["Contacts","Deals","Companies"]'::jsonb,
    'generic',
    23,
    true,
    false,
    'hubspot'
  ),
  (
    'github',
    'GitHub',
    'Engineering',
    'Repos, pull requests, and issues',
    'github',
    'public',
    true,
    '["Repos","PRs","Issues"]'::jsonb,
    'generic',
    24,
    true,
    false,
    'github'
  ),
  (
    'teams',
    'Microsoft Teams',
    'Communication',
    'Teams, channels, and chat',
    'teams',
    'public',
    true,
    '["Teams","Channels","Chat"]'::jsonb,
    'generic',
    25,
    true,
    false,
    'microsoft_teams'
  ),
  (
    'stripe',
    'Stripe',
    'Commerce',
    'Customers, invoices, and balance',
    'stripe',
    'public',
    true,
    '["Customers","Invoices","Subscriptions"]'::jsonb,
    'generic',
    26,
    true,
    false,
    'stripe'
  ),
  (
    'salesforce',
    'Salesforce',
    'Commerce',
    'Accounts, contacts, and opportunities',
    'salesforce',
    'public',
    true,
    '["Accounts","Contacts","Opportunities"]'::jsonb,
    'generic',
    27,
    true,
    false,
    'salesforce'
  ),
  (
    'linear',
    'Linear',
    'Engineering',
    'Issues, projects, and teams',
    'linear',
    'public',
    true,
    '["Issues","Projects","Teams"]'::jsonb,
    'generic',
    28,
    true,
    false,
    'linear'
  ),
  (
    'jira',
    'Jira',
    'Engineering',
    'Projects and issues',
    'jira',
    'public',
    true,
    '["Issues","Projects","Search"]'::jsonb,
    'generic',
    29,
    true,
    false,
    'jira'
  ),
  (
    'shopify',
    'Shopify',
    'Commerce',
    'Orders, products, and customers',
    'shopify',
    'public',
    true,
    '["Orders","Products","Customers"]'::jsonb,
    'generic',
    30,
    true,
    true,
    'shopify'
  )
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  icon = excluded.icon,
  featured = excluded.featured,
  actions = excluded.actions,
  panel_type = excluded.panel_type,
  display_order = excluded.display_order,
  enabled = excluded.enabled,
  coming_soon = excluded.coming_soon,
  provider_toolkit_id = excluded.provider_toolkit_id;
